site_name: My Docs

theme:
    name: readthedocs

nav:
    - HOME: 'Client/index.md'
    - API: 'Client/api.md'
    - FRONTEND: 'Client/front.md'
    - BACKEND: 'Client/back.md'
    - CONTRIBUTE: 'Client/contribute.md'